### ISSUE TITLE
VFS improvement tracker 

### ISSUE THREAD

**Issue by netbsduser** [Keyronex/keyronex-archive#6]
- [x] Keyronex/keyronex-archive#11 
- [x] Keyronex/keyronex-archive#10 
- [x] Keyronex/Keyronex#13 
- [ ] Keyronex/keyronex-archive#7
